Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
soft_data = pub_agg.real_vs_private_soft_error_bars()
g = plot_line_nested_epsilon_dict_error_bars(soft_data)
g.set(title="")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn [13], line 1[0m
[0;32m----> 1[0m soft_data [38;5;241m=[39m [43mpub_agg[49m[38;5;241;43m.[39;49m[43mreal_vs_private_soft_error_bars[49m[43m([49m[43m)[49m
[1;32m      2[0m g [38;5;241m=[39m plot_line_nested_epsilon_dict_error_bars(soft_data)
[1;32m      3[0m g[38;5;241m.[39mset(title[38;5;241m=[39m[38;5;124m"[39m[38;5;124m"[39m)

File [0;32m~/work/SynRD/SynRD/papers/publication_aggregator.py:136[0m, in [0;36mPublicationAggregator.real_vs_private_soft_error_bars[0;34m(self)[0m
[1;32m    131[0m [38;5;28;01mdef[39;00m [38;5;21mreal_vs_private_soft_error_bars[39m([38;5;28mself[39m):
[1;32m    132[0m     [38;5;124;03m"""[39;00m
[1;32m    133[0m [38;5;124;03m    Calculate percent matching of soft findings on[39;00m
[1;32m    134[0m [38;5;124;03m    real vs private across epsilons and synthesizers[39;00m
[1;32m    135[0m [38;5;124;03m    """[39;00m
[0;32m--> 136[0m     [38;5;28;01mfrom[39;00m [38;5;21;01mstatsmodels[39;00m[38;5;21;01m.[39;00m[38;5;21;01mstats[39;00m[38;5;21;01m.[39;00m[38;5;21;01mweightstats[39;00m [38;5;28;01mimport[39;00m DescrStatsW
[1;32m    138[0m     [38;5;66;03m# pub_id -> percentages_at_epsilon[39;00m
[1;32m    139[0m     [38;5;66;03m# soft_means = {}[39;00m
[1;32m    140[0m     [38;5;66;03m# soft_lower_cis = {}[39;00m
[1;32m    141[0m     [38;5;66;03m# soft_upper_cis = {}[39;00m
[1;32m    142[0m     soft_data [38;5;241m=[39m {}

[0;31mModuleNotFoundError[0m: No module named 'statsmodels'
ModuleNotFoundError: No module named 'statsmodels'

